import { Component } from '@angular/core';
import {FormBuilder, FormGroup, ReactiveFormsModule, Validators} from '@angular/forms';
import { Router } from '@angular/router';
import { TransactionService } from '../../Services/transaction.service';
import { Transaction } from '../../Models/transaction.model';
import {NgIf} from "@angular/common";

@Component({
  selector: 'app-create-transaction',
  templateUrl: './create-transaction.component.html',
  standalone: true,
  imports: [
    ReactiveFormsModule,
    NgIf
  ],
  styleUrls: ['./create-transaction.component.css']
})
export class CreateTransactionComponent {

  transactionForm: FormGroup;

  constructor(
    private fb: FormBuilder,
    private transactionService: TransactionService,
    private router: Router
  ) {
    this.transactionForm = this.fb.group({
      product_Id: ['', Validators.required],
      transaction_Type: ['', Validators.required],
      quantity: ['', [Validators.required, Validators.min(1)]],
      transaction_Date: ['', Validators.required]
    });
  }

  onSubmit(): void {
    if (this.transactionForm.valid) {
      const formValue = this.transactionForm.value;

      // Map form values to match the expected backend model
      const newTransaction: Transaction = {
        // @ts-ignore
        transaction_Id: null, // Assuming this is generated by the backend
        product_Id: formValue.product_Id,
        transaction_Type: formValue.transaction_Type,
        quantity: formValue.quantity,
        transaction_Date: formValue.transaction_Date
      };
      console.log('New transaction:', newTransaction);

      this.transactionService.addTransaction(newTransaction).subscribe(
        () => {
          console.log('Transaction created successfully');
          this.router.navigate(['/transactions']);
        },
        error => {
          console.error('Error creating transaction:', error);
        }
      );
    }
  }
}
